include:
  project: mnt/ci
  file: front/ci.yaml
  ref: ${MNT_CI_REF}

variables:
  DEV_BASE_DOMAIN: <%= projectName %>.kube1.ktsdev2.ru
  DEV_API_DOMAIN: <%= projectName %>.kube1.ktsdev2.ru
  PROD_DOMAIN: <%= projectName %>.ru-prod2.kts.studio
